//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetkiliServisOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbYetkiliServisEntities : DbContext
    {
        public DbYetkiliServisEntities()
            : base("name=DbYetkiliServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblCari> TblCari { get; set; }
        public virtual DbSet<TblCariTür> TblCariTür { get; set; }
        public virtual DbSet<TblDepartman> TblDepartman { get; set; }
        public virtual DbSet<TblDepo> TblDepo { get; set; }
        public virtual DbSet<TblKasa> TblKasa { get; set; }
        public virtual DbSet<TblKasaCikis> TblKasaCikis { get; set; }
        public virtual DbSet<TblKasaDurum> TblKasaDurum { get; set; }
        public virtual DbSet<TblKasaGiris> TblKasaGiris { get; set; }
        public virtual DbSet<TblKullanici> TblKullanici { get; set; }
        public virtual DbSet<TblNotlar> TblNotlar { get; set; }
        public virtual DbSet<TblServisDurum> TblServisDurum { get; set; }
        public virtual DbSet<TblServisler> TblServisler { get; set; }
        public virtual DbSet<TblSiparisler> TblSiparisler { get; set; }
        public virtual DbSet<TblStok> TblStok { get; set; }
        public virtual DbSet<TblVeresiye> TblVeresiye { get; set; }
        public virtual DbSet<TblVeresiyeDurum> TblVeresiyeDurum { get; set; }
    }
}
