//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetkiliServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCari()
        {
            this.TblKasaCikis = new HashSet<TblKasaCikis>();
            this.TblKasaGiris = new HashSet<TblKasaGiris>();
            this.TblSiparisler = new HashSet<TblSiparisler>();
            this.TblStok = new HashSet<TblStok>();
            this.TblVeresiye = new HashSet<TblVeresiye>();
            this.TblServisler = new HashSet<TblServisler>();
        }
    
        public int Id { get; set; }
        public string CariKod { get; set; }
        public string CariAdiSoyadi { get; set; }
        public string CariTelefon { get; set; }
        public string CariTelefon2 { get; set; }
        public string CariAdres { get; set; }
        public string CariIl { get; set; }
        public string CariIlce { get; set; }
        public string CariPostaKod { get; set; }
        public string CariVergiDaire { get; set; }
        public string CariVergiNo { get; set; }
        public Nullable<int> CariTür { get; set; }
        public string CariAciklama { get; set; }
        public string KayitEden { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public string Aciklama { get; set; }
        public string CariMailAdres { get; set; }
        public Nullable<bool> CariDurum { get; set; }
    
        public virtual TblCariTür TblCariTür { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKasaCikis> TblKasaCikis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKasaGiris> TblKasaGiris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSiparisler> TblSiparisler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStok> TblStok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVeresiye> TblVeresiye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblServisler> TblServisler { get; set; }
    }
}
