//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetkiliServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKullanici
    {
        public int Id { get; set; }
        public string KullanıcıAdi { get; set; }
        public string KullaniciSifre { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public string Aciklama { get; set; }
        public string KullaniciMail { get; set; }
        public Nullable<int> DepartmanId { get; set; }
        public Nullable<bool> YetkiDurum { get; set; }
    
        public virtual TblDepartman TblDepartman { get; set; }
    }
}
