//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetkiliServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotlar
    {
        public int Id { get; set; }
        public string NotBaslik { get; set; }
        public string Noticerik { get; set; }
        public Nullable<System.DateTime> NotTarih { get; set; }
        public Nullable<bool> NotDurum { get; set; }
        public string Aciklama { get; set; }
        public string KayitEden { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
    }
}
