//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetkiliServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSiparisler
    {
        public int Id { get; set; }
        public Nullable<int> CariId { get; set; }
        public Nullable<int> StokId { get; set; }
        public Nullable<int> SiparisMiktar { get; set; }
        public System.DateTime TeslimTarih { get; set; }
        public Nullable<decimal> SiparisTutar { get; set; }
        public Nullable<bool> SiparisDurum { get; set; }
        public string KayitEden { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public string Aciklama { get; set; }
    
        public virtual TblCari TblCari { get; set; }
        public virtual TblStok TblStok { get; set; }
    }
}
