//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetkiliServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblStok()
        {
            this.TblKasaCikis = new HashSet<TblKasaCikis>();
            this.TblKasaGiris = new HashSet<TblKasaGiris>();
            this.TblServisDurum = new HashSet<TblServisDurum>();
            this.TblSiparisler = new HashSet<TblSiparisler>();
            this.TblVeresiye = new HashSet<TblVeresiye>();
        }
    
        public int Id { get; set; }
        public string StokNo { get; set; }
        public string StokAdi { get; set; }
        public string StokMarka { get; set; }
        public string StokModel { get; set; }
        public Nullable<int> StokMiktar { get; set; }
        public Nullable<decimal> StokAlisFiyat { get; set; }
        public Nullable<decimal> StokSatisFiyat { get; set; }
        public Nullable<int> DepoId { get; set; }
        public string KayitEden { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> KritikStokDurum { get; set; }
        public Nullable<int> AliciCari { get; set; }
        public string Aciklama { get; set; }
    
        public virtual TblCari TblCari { get; set; }
        public virtual TblDepo TblDepo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKasaCikis> TblKasaCikis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKasaGiris> TblKasaGiris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblServisDurum> TblServisDurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSiparisler> TblSiparisler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVeresiye> TblVeresiye { get; set; }
    }
}
