//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetkiliServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVeresiye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblVeresiye()
        {
            this.TblVeresiyeDurum = new HashSet<TblVeresiyeDurum>();
        }
    
        public int Id { get; set; }
        public string VeresiyeKod { get; set; }
        public Nullable<int> CariId { get; set; }
        public Nullable<int> StokId { get; set; }
        public Nullable<decimal> VeresiyeTutar { get; set; }
        public Nullable<System.DateTime> VeresiyeTarih { get; set; }
        public Nullable<System.DateTime> OdemeTarih { get; set; }
        public Nullable<decimal> OdenecekTutar { get; set; }
        public string KayitEden { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> UrunMiktari { get; set; }
    
        public virtual TblCari TblCari { get; set; }
        public virtual TblStok TblStok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVeresiyeDurum> TblVeresiyeDurum { get; set; }
    }
}
