//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetkiliServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVeresiyeDurum
    {
        public int Id { get; set; }
        public Nullable<int> VeresiyeId { get; set; }
        public Nullable<decimal> OdemeTutar { get; set; }
        public Nullable<decimal> KalanTutar { get; set; }
        public Nullable<System.DateTime> OdemeTarih { get; set; }
        public string KayitEden { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public string Aciklama { get; set; }
    
        public virtual TblVeresiye TblVeresiye { get; set; }
    }
}
